name: ramp_shopper_intention
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - notebook
  - scikit-learn
  - seaborn
  
  -pip
  - pip:
    - ramp-workflow
